<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">put</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgaWRjID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQpJRGF0YSBhc3NldERvYyA9
IElEYXRhVXRpbC5nZXRJRGF0YShpZGMsIkFzc2V0Iik7DQpDYWNoZU1hbmFnZXIgY2FjaGVNYW5h
Z2VyID0gKENhY2hlTWFuYWdlcikgSURhdGFVdGlsLmdldChpZGMsImNhY2hlTWFuYWdlciIpOw0K
RWhjYWNoZSBjYWNoZSA9IChFaGNhY2hlKSBJRGF0YVV0aWwuZ2V0KGlkYywiY2FjaGUiKTsNClN0
cmluZyBrZXkgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGlkYywia2V5Iik7DQppZGMuZGVzdHJveSgp
Ow0KDQpFbGVtZW50IGVsZW0gPSBuZXcgRWxlbWVudChrZXksYXNzZXREb2MpOw0KDQpjYWNoZS5w
dXQoZWxlbSk7DQoNCklEYXRhQ3Vyc29yIGlkYzEgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNCklE
YXRhVXRpbC5wdXQoaWRjLCAiY2FjaGUiLCBjYWNoZSk7DQppZGMxLmRlc3Ryb3koKTs=</value>
</Values>
